trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: StaticWebAppSecrets
  - name: REACT_APP_API_URL
    value: 'https://edusync-backend-abhi-hjeph9aze0gvhyc7.eastus2-01.azurewebsites.net/api'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'
    workingDirectory: eduSync-frontend/frontend
    env:
      REACT_APP_API_URL: $(REACT_APP_API_URL)

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'eduSync-frontend/frontend'
      output_location: 'build'
      azure_static_web_apps_api_token: $(deployment_token)
